CREATE DATABASE CADASTRO
GO

USE CADASTRO
GO

CREATE TABLE CLIENTE(
	IDCLIENTE INT PRIMARY KEY IDENTITY,
	NOME VARCHAR(50) NOT NULL,
	CPF VARCHAR(11) NOT NULL UNIQUE,
	SEXO VARCHAR(20) NOT NULL,
	NASCIMENTO DATE NOT NULL,
	NOTIFICACAO BIT NOT NULL DEFAULT 0
)
GO